# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  程猿薇茑
subtitle: 快乐分享，分享快乐
name: 程猿薇茑 
email: bigbirditedu@163.com
description: 本站是程猿薇茑的分享博客,内容涵盖生活故事、Java编程、web前端、人工智能算法等相关知识的研究与分享
keywords: Spring,Spring mvc,Spring boot,spring Cloud,Mybatis,Mysql,MongoDB,Hbase,Docker,java架构师,分布式存储,Developer,Programmer,Coder,Geek,IT技术博客,Java,Python,机器学习
encoding: "utf-8"
favicon: favicon.ico 

repository: bigbirditedu/bigbirditedu.github.io
github_url: https://github.com/bigbirditedu
url: http://www.bigbirditedu.com
enforce_ssl: bigbirditedu.com

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:

  -
    href: /life.html
    label: 生活
    target: _self

  -
    href: /arch.html
    label: 架构
    target: _self

  -
    href: /link.html
    label: 友链
    target: _self

  -
    href: /about.html
    label: 关于
    target: _self

# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  -
    href: /spring-boot.html
    label: Spring
    target: _self
    subnav:

      -
        subHref: /spring-boot.html
        subLabel: Spring Boot

      -
        subHref: /spring-cloud.html
        subLabel: Spring Cloud
        
      -
        subHref: /spring-boot.html
        subLabel: Spring MVC

      -
        subHref: /spring-cloud.html
        subLabel: Spring Core
        
  -
    href: /spring-cloud.html
    label: 数据库
    target: _self
    subnav:

      -
        subHref: /spring-boot.html
        subLabel: Mysql

      -
        subHref: /spring-cloud.html
        subLabel: Hbase
        
      -
        subHref: /spring-boot.html
        subLabel: MongoDB

  -
    
    href: http://www.justdojava.com
    label: 前端
    target: _blank
    subnav:

      -
        subHref: /java.html
        subLabel: web前端基础
        
      -
        subHref: http://www.justdojava.com
        subLabel: web前端进阶
        target: _blank

  -
    href: /archives.html
    label: 人工智能
    target: _blank
    subnav:

      -
        subHref: /python.html
        subLabel: Python 编程
        
      -
        subHref: http://www.justdopython.com
        subLabel: 机器学习
        target: _blank
        
  -
    href: /archives.html
    label: Archives
    target: _self



# labels. my blog key words
labels:

  -
    href: /fastdfs.html
    label: Machine Learning
    target: _blank

  -
    href: /mongodb.html
    label: JVM
    target: _blank

  -
    href: /docker.html
    label: Docker
    target: _blank

  -
    href: /open-source.html
    label: Java  
    target: _blank


# selected articles
classes:

  -
    href: /life.html
    name: 我的故事
    describe: 生活就是故事，故事就是生活

  -
    href: /it.html
    name: 业界深度报道
    describe: IT大佬，互联网知名公司的故事

  -
    href: /arch.html
    name: 程序员之路
    describe: 一个软件工程师的自我修养


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: bigbirditedu
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: bigbirditedu
    repo: bigbirditedu.github.io
    oauth:
        client_id: 81653c91db1dc332bdf9
        client_secret: d6d3544d20ade44c3e1c50e45308cd75346906de
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: bigbirditedu
    repo: bigbirditedu.github.io
    clientID: 0738a3bd42783517d627
    clientSecret: 559df037c39b15b923b91f2f319a2b67f7f92d55

# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

theme: jekyll-theme-cayman
